### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by mroberts1** [kconner/gloggery#1]
I'm trying to install this on MacOS (10.15) but after cloning the GitHub repo and running <make install> I just get this message: 

/Users/dokoissho/bin/gloggery: No such file or directory
make: *** [install] Error 1

I have installed Go 1.15.2

Any idea why I can't install gloggery?

**Comment by kconner** [comment]
I think the error suggests the folder /Users/dokoissho/bin does not exist. You could create that, or make with prefix=/usr/local to install to /usr/local/bin, supposing that exists.

**Comment by mroberts1** [comment]
Thanks, that seems to have fixed it!
