### ISSUE TITLE
Release a binary on github

### ISSUE THREAD

**Issue by m040601** [kconner/gloggery#2]
Thanky for your work on this promising tool.
Eager to try this for hosting a gemini blog, on less powered devices, like the raspberry pi.

It's not practical to constantly download the half giga go distro and recompile go binaries on these ARM devices.

Any chance you could actualy release it as a binary on github ?

Releasing a binary, just makes your tool available for someone who just wants to check it out quickly, compare it with others.

Not everyone has the entire go distribution installed or as a simple user is familiar with compiling.Besides that releasing a binary, would make it easier for others to create a package for a Linux distro, based on the binary (ex. Ubuntu, Archlinux AUR).i

Do you know you can automate this with github actions ?
Do you know this tool, https://github.com/goreleaser/goreleaser ?

https://help.github.com/en/articles/creating-releases
you can also use:

travis, https://blog.questionable.services/article/build-go-binaries-travis-ci-github/
circleci, https://circleci.com/blog/publishing-to-github-releases-via-circleci/

**Comment by kconner** [comment]
Thanks very much for the suggestion and links!

https://github.com/kconner/gloggery/releases/tag/v1.0
